# Generated by Django 5.0.7 on 2024-08-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='forms', to='forms.field'),
        ),
    ]
