# Generated by Django 5.0.7 on 2024-08-05 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='pipline',
        ),
        migrations.RemoveField(
            model_name='form',
            name='pipline',
        ),
        migrations.RemoveField(
            model_name='field',
            name='form',
        ),
        migrations.AddField(
            model_name='field',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='fields',
            field=models.ManyToManyField(related_name='forms', to='forms.field'),
        ),
        migrations.AddField(
            model_name='form',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField()),
                ('questions_responding_duration', models.PositiveBigIntegerField(help_text='Response duration time in minutes')),
                ('start_datetime', models.DateTimeField()),
                ('stop_datetime', models.DateTimeField()),
                ('hide_previous_button', models.BooleanField()),
                ('hide_next_button', models.BooleanField()),
                ('is_private', models.BooleanField()),
                ('password', models.CharField(max_length=50, null=True)),
                ('forms', models.ManyToManyField(related_name='pipelines', to='forms.form')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='pipeline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.pipeline'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pipline',
        ),
    ]
