# Generated by Django 5.0.7 on 2024-08-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
