# Generated by Django 5.0.7 on 2024-08-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_delete_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipline',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pipline',
            name='stop_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
