# Generated by Django 5.0.7 on 2024-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_form_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'short input include a text'), (2, 'long input include a text'), (3, 'choose one or multiple choises'), (4, 'numeric input')]),
        ),
    ]
