# Generated by Django 5.0.7 on 2024-08-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='number_of_views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
