# Generated by Django 5.0.7 on 2024-08-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_pipline_start_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipline',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
