# Generated by Django 5.0.7 on 2024-08-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_remove_category_forms_remove_category_pipelines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
