# Generated by Django 5.0.7 on 2024-08-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
