# Generated by Django 5.0.7 on 2024-08-10 11:13

import responses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_pipelinesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinesubmission',
            name='responses',
            field=models.JSONField(default=responses.models.get_default_responses),
        ),
    ]
