# Generated by Django 5.0.7 on 2024-08-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0005_remove_pipelinesubmission_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinesubmission',
            name='session',
        ),
        migrations.RemoveField(
            model_name='response',
            name='session',
        ),
        migrations.AddField(
            model_name='pipelinesubmission',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
