# Generated by Django 5.0.7 on 2024-08-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0007_alter_response_form_alter_response_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='pipeline_submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='responses.pipelinesubmission'),
            preserve_default=False,
        ),
    ]
