# Generated by Django 5.0.7 on 2024-08-12 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_remove_category_slug'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='pipeline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.pipeline'),
            preserve_default=False,
        ),
    ]
